import test from 'node:test';import assert from 'node:assert/strict';
import {fixtures,extractFixture,validateFields,buildReport,isValidDate,makeDraft} from '../src/core.mjs';
const fields={worked_at:'2026-09-07',parcel_id:'p1',crop:'상추',work_type:'관수',amount:20,unit:'L'};
test('30 fixtures, deterministic repeatable extraction with safe source',()=>{assert.ok(fixtures.length>=30);for(const f of fixtures){assert.deepEqual(extractFixture(f.id),extractFixture(f.id));const d=extractFixture(f.id).draft;assert.equal(d.raw_input,f.text);assert.equal(d.source,'synthetic_text');assert.equal(d.regulatory_status,'not_checked');assert.ok(d.warnings.length);}});
test('normal extracts all fields',()=>{const d=extractFixture('normal').draft;for(const k in fields)assert.equal(d[k],fields[k]);assert.deepEqual(d.missing,[]);});
test('missing required recomputed from actual values',()=>{const d=makeDraft('normal',{});assert.deepEqual(d.missing,['worked_at','parcel_id','crop','work_type']);assert.ok(d.question);});
test('missing crop never inferred from parcel',()=>{assert.equal(makeDraft('normal',{parcel_id:'p1'}).crop,null);});
test('multiple work and quantity require human resolution',()=>{const d=extractFixture('multiple').draft;assert.equal(d.work_type,null);assert.equal(d.amount,null);assert.ok(d.question);});
test('ambiguous text does not guess yesterday',()=>{const d=extractFixture('ambiguous').draft;assert.equal(d.worked_at,null);assert.equal(d.parcel_id,null);assert.equal(d.work_type,null);});
test('spray remains unchecked',()=>{const d=extractFixture('spray').draft;assert.equal(d.work_type,'방제');assert.ok(d.warnings.some(w=>w.includes('안전 판정이 아님')));});
test('harvest decimal and unit',()=>{const d=extractFixture('harvest').draft;assert.equal(d.amount,12.5);assert.equal(d.unit,'kg');});
test('year-end preserved without rolling into next year',()=>assert.equal(extractFixture('year-end').draft.worked_at,'2026-12-31'));
test('leap date and invalid date',()=>{assert.equal(extractFixture('leap-day').draft.worked_at,'2024-02-29');assert.equal(extractFixture('invalid-date').draft.worked_at,null);});
test('quantity without unit not guessed',()=>{const d=extractFixture('no-unit').draft;assert.equal(d.amount,null);assert.equal(d.unit,null);});
test('multi parcel and crop do not assign combined amount',()=>{assert.equal(extractFixture('multi-parcel').draft.parcel_id,null);assert.equal(extractFixture('multi-crop').draft.crop,null);assert.equal(extractFixture('multi-crop').draft.amount,null);});
for(const date of ['2026-02-29','2026-04-31','0000-01-01','2026-13-01','2026-00-01','2026-01-00','26-01-01','2026-1-1','2026-09-07T00:00:00Z','nope'])test('reject invalid date '+date,()=>{assert.equal(isValidDate(date),false);assert.throws(()=>validateFields({...fields,worked_at:date}));});
for(const date of ['2024-02-29','2000-02-29','2026-12-31','2027-01-01'])test('accept valid date '+date,()=>assert.equal(isValidDate(date),true));
for(const amount of [0,-1,Infinity,NaN,'12',{},[]])test('reject non-positive/non-numeric amount '+String(amount),()=>assert.throws(()=>validateFields({...fields,amount})));
for(const [k,v] of [['parcel_id','private-farm'],['crop','unknown'],['work_type','제어'],['unit','bottle'],['gps','35,127'],['raw_input','private'],['farmer_name','name'],['address','address']])test('privacy and enum allowlist '+k,()=>assert.throws(()=>validateFields({...fields,[k]:v})));
test('null amount accepted independently; missing remains required fields only',()=>{const d=makeDraft('normal',{...fields,amount:null});assert.deepEqual(d.missing,[]);assert.ok(d.warnings.some(w=>w.includes('수량')));});
test('unknown fixture rejected',()=>assert.throws(()=>extractFixture('private'),{status:404}));
test('report latest correction chain only, all history unchanged',()=>{const records=[{event_id:'a',supersedes:null},{event_id:'b',supersedes:'a'},{event_id:'c',supersedes:'b'},{event_id:'d',supersedes:null}];const before=JSON.stringify(records);const r=buildReport(records);assert.deepEqual(r.event_ids,['c','d']);assert.ok(r.warning.includes('공식 인증서식 아님'));assert.equal(JSON.stringify(records),before);assert.ok(r.markdown.includes('c'));});
