import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
import {emptyDraft,normalizeDraft,extractDraft,capabilitiesAI,ENDPOINTS,DRAFT_SCHEMA} from '../src/app/ai.mjs';
const profile={parcels:[{id:'house-3',name:'3번 하우스',aliases:['삼번 하우스'],crop:'토마토'},{id:'upper',name:'윗밭',aliases:[],crop:'고추'}]};
const context={profile,workedAt:'2026-09-07'};
function provider(raw,overrides={}) {const calls=[];return {calls,fetchImpl:async(url,options)=>{calls.push({url,options});assert.equal(options.redirect,'error');if(url===ENDPOINTS.tags)return Response.json({models:[{name:'qwen3:4b',size:2497293931,...overrides.tags}]});if(url===ENDPOINTS.show)return Response.json({details:{format:'gguf'},...overrides.show});if(url===ENDPOINTS.generate)return Response.json({done:true,response:typeof raw==='string'?raw:JSON.stringify(raw)});throw new Error('unexpected endpoint');}};}
test('emptyDraft contract and invalid dates',()=>{assert.equal(emptyDraft('2026-02-30').worked_at,null);assert.equal(emptyDraft('2026-09-07').worker_count,null);assert.deepEqual(Object.keys(emptyDraft()).sort(),DRAFT_SCHEMA.required.slice().sort());});
test('schema forcing and exact fixed endpoint ordering',async()=>{const p=provider(emptyDraft());const r=await extractDraft({...context,text:'3번 하우스에서 물 줬어요.'},p);assert.equal(r.engine,'ollama:qwen3:4b');assert.deepEqual(p.calls.map(c=>c.url),Object.values(ENDPOINTS));const b=JSON.parse(p.calls[2].options.body);assert.equal(b.think,false);assert.equal(b.options.temperature,0);assert.ok(b.options.num_predict<=1500);assert.equal(b.format.additionalProperties,false);});
test('remote tags, remote show and cloud metadata fail before generate',async()=>{for(const overrides of [{tags:{remote_host:'https://ollama.com'}},{tags:{remote_model:'remote'}},{show:{remote_model:'qwen3:4b'}},{show:{remote_host:'https://ollama.com'}},{tags:{model:'qwen3:4b-cloud'}}]){const p=provider(emptyDraft(),overrides);const r=await extractDraft({...context,text:'윗밭 풀 뽑았어요'},p);assert.equal(r.engine,'local-fallback');assert.ok(r.warnings[0].includes('AI 결과가 아닙니다'));assert.ok(!p.calls.some(c=>c.url===ENDPOINTS.generate));}});
test('redirect responses rejected and no next endpoint',async()=>{let calls=0;const r=await extractDraft({...context,text:'물 줬어요'},{fetchImpl:async()=>{calls++;return {ok:true,redirected:true,url:'https://example.invalid',json:async()=>({})};}});assert.equal(r.engine,'local-fallback');assert.equal(calls,1);});
test('timeout abort and malformed response explicitly fallback',async()=>{let aborted=false;const r=await extractDraft({...context,text:'3번 하우스에서 관수 19분'}, {timeoutMs:15,fetchImpl:(_url,{signal})=>new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>{aborted=true;reject(new Error('aborted'));},{once:true});})});assert.equal(r.engine,'local-fallback');assert.ok(aborted);assert.equal(r.draft.duration_minutes,19);assert.match(r.warnings[0],/시간 초과/);for(const value of ['invalid','{}','[]'])assert.equal((await extractDraft({...context,text:'윗밭 제초'},provider(value))).engine,'local-fallback');});
test('normalize allowlist, types, bounds and no unknown 0 guesses',()=>{const d=normalizeDraft({...emptyDraft(),parcel_id:'unknown',crop:'배',work_type:'비밀작업',worker_count:99,weather:'맑음',area_m2:500,harvest_amount:0,duration_minutes:20,inputs:[{action:'send',kind:'other'}],extra:'no'}, {...context,text:'아직 뭘 했는지 말을 안 했어요'});assert.equal(d.parcel_id,null);for(const k of ['crop','weather','worker_count','area_m2','harvest_amount','duration_minutes','work_type'])assert.equal(d[k],null,k);assert.deepEqual(d.inputs,[]);assert.ok(!('extra'in d));});
test('relative date, multi-work and liters separated from harvest/duration',()=>{const d=normalizeDraft({}, {...context,text:'어제 3번 하우스에서 물 80리터를 줬고 30분 동안 풀 뽑았어요. 관수도 했어요.'});assert.equal(d.worked_at,'2026-09-06');assert.equal(d.work_type,'관수·제초');assert.equal(d.duration_minutes,30);assert.equal(d.harvest_amount,null);assert.match(d.details,/80리터/);});
test('human answers remain unless an explicit correction names a replacement',()=>{const previousDraft={...emptyDraft('2026-09-04'),parcel_id:'upper',crop:'고추',work_type:'제초',worker_count:2,duration_minutes:20};let d=normalizeDraft({}, {...context,previousDraft,text:'날씨는 흐림이었어요'});assert.equal(d.parcel_id,'upper');assert.equal(d.worker_count,2);assert.equal(d.worked_at,'2026-09-04');d=normalizeDraft({}, {...context,previousDraft,text:'아니 작업 시간은 45분으로 정정할게요'});assert.equal(d.duration_minutes,45);assert.equal(d.worked_at,'2026-09-04');assert.equal(d.worker_count,2);});
test('OCR is reference only, model details cannot inject advice',()=>{const d=normalizeDraft({...emptyDraft(),work_type:'방제',inputs:[{action:'use',kind:'pesticide',name:'샘플농약',quantity:2,unit:'병',dilution:null}],details:'권장 농약을 살포하세요'}, {...context,text:'사진만 붙였어요.\n[OCR 참고] 샘플농약 2병 방제'});assert.deepEqual(d.inputs,[]);assert.equal(d.work_type,null);assert.ok(!d.details.includes('권장'));});
test('purchase not use and unknown quantity remains null',()=>{const d=normalizeDraft({inputs:[{action:'purchase',kind:'fertilizer',name:'복합비료',quantity:2,unit:'포',dilution:null},{action:'use',kind:'fertilizer',name:'복합비료',quantity:2,unit:'포',dilution:null}]},{...context,text:'복합비료를 샀어요. 아직 안 썼어요.'});assert.equal(d.inputs.length,1);assert.equal(d.inputs[0].action,'purchase');assert.equal(d.inputs[0].quantity,null);});
test('fallback varies with actual text, never fixtures',async()=>{const fail={fetchImpl:async()=>{throw new Error('offline');}};const a=await extractDraft({...context,text:'그제 윗밭에서 제초 17분'},fail);const b=await extractDraft({...context,text:'3번 하우스에서 토마토 23kg 수확했어요'},fail);assert.equal(a.draft.duration_minutes,17);assert.equal(a.draft.worked_at,'2026-09-05');assert.equal(b.draft.harvest_amount,23);assert.equal(b.draft.harvest_unit,'kg');assert.notDeepEqual(a.draft,b.draft);});
const samples=[
 {id:'natural-multiple',text:'어제 3번 하우스에서 물 주고 풀도 뽑았어. 한 30분 걸렸네.',expected:{worked_at:'2026-09-06',parcel_id:'house-3',crop:null,work_type:'관수·제초',duration_minutes:30,harvest_amount:null}},
 {id:'purchase-not-use',text:'윗밭용 복합비료 2포 사왔어. 아직 밭에는 안 뿌렸어.',expected:{parcel_id:'upper',work_type:'자재구매',harvest_amount:null},inputs:[{action:'purchase',name:'복합비료',quantity:2,unit:'포'}],noUse:true},
 {id:'water-vs-harvest',text:'오늘 3번 하우스 토마토에 물 80리터 줬고 관수는 25분 했어. 수확은 안 했어.',expected:{parcel_id:'house-3',duration_minutes:25,harvest_amount:null,harvest_unit:null,work_type:'관수'}},
 {id:'harvest-correction',text:'아니, 수확량은 12kg이 아니라 18kg으로 정정할게요.',previousDraft:{...emptyDraft('2026-09-05'),parcel_id:'upper',crop:'고추',work_type:'수확',harvest_amount:12,harvest_unit:'kg',worker_count:2},expected:{worked_at:'2026-09-05',parcel_id:'upper',crop:'고추',harvest_amount:18,harvest_unit:'kg',worker_count:2}},
 {id:'ocr-not-usage',text:'사진만 첨부했어요. 실제로 사용했는지는 아직 말하지 않았어요.\n[OCR 참고] 샘플농약 500ml 1000배 희석, 방제',expected:{work_type:null,worker_count:null,harvest_amount:null},inputs:[]}
];
test('live local inference: five non-sensitive examples; report measured failures, no accuracy guarantee',{skip:process.env.FARMLOG_AI_LIVE!=='1',timeout:210000},async()=>{
 const startedAt=new Date().toISOString();const cap=await capabilitiesAI();const tags=await fetch(ENDPOINTS.tags,{redirect:'error',signal:AbortSignal.timeout(5000)}).then(r=>r.json());const show=await fetch(ENDPOINTS.show,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'qwen3:4b'}),redirect:'error',signal:AbortSignal.timeout(5000)}).then(r=>r.json());const results=[];
 for(const sample of samples){const start=performance.now();const result=await extractDraft({...context,text:sample.text,previousDraft:sample.previousDraft});const latency_ms=Math.round(performance.now()-start);const checks=Object.entries(sample.expected).map(([field,expected])=>({field,expected,actual:result.draft[field],pass:result.draft[field]===expected}));if(sample.inputs){for(const expected of sample.inputs)checks.push({field:'inputs',expected,actual:result.draft.inputs,pass:result.draft.inputs.some(i=>Object.entries(expected).every(([k,v])=>i[k]===v))});if(!sample.inputs.length)checks.push({field:'inputs',expected:[],actual:result.draft.inputs,pass:result.draft.inputs.length===0});}if(sample.noUse)checks.push({field:'no-use',pass:!result.draft.inputs.some(i=>i.action==='use')});checks.push({field:'actual-local-ai',pass:result.engine==='ollama:qwen3:4b'});results.push({id:sample.id,text:sample.text,previousDraft:sample.previousDraft??null,latency_ms,...result,checks,passed:checks.every(c=>c.pass)});console.log(JSON.stringify({id:sample.id,latency_ms,engine:result.engine,failures:checks.filter(c=>!c.pass)}));}
 const checks=results.flatMap(r=>r.checks);const report={startedAt,completedAt:new Date().toISOString(),scope:'비민감 합성 문장 5건. 실제 농가 검증/안전성/모델 일반 정확도 주장 아님.',endpoints:ENDPOINTS,model:'qwen3:4b',installedModels:tags.models.map(m=>({name:m.name,remote:!!(m.remote_host||m.remote_model)})),localVerification:{capabilities:cap,format:show.details?.format,remote_host:show.remote_host??null,remote_model:show.remote_model??null},selectedWorkedAt:context.workedAt,profile,summary:{cases:results.length,passed:results.filter(r=>r.passed).length,checks:checks.length,passedChecks:checks.filter(c=>c.pass).length,localAI:results.filter(r=>r.engine==='ollama:qwen3:4b').length},results};await writeFile(new URL('../evidence/farmer-ai-live-v2.json',import.meta.url),JSON.stringify(report,null,2)+'\n');assert.equal(results.length,5);
});

test('server multiline OCR remains reference and initial selected date allows yesterday',()=>{const d=normalizeDraft({work_type:'방제',inputs:[{action:'use',kind:'pesticide',name:'샘플농약',quantity:2,unit:'병'}]},{...context,text:'사진을 첨부했어요.\n[신뢰하지 않는 사진 OCR 참고자료: 작업/사용 사실로 확정하지 말 것]\n샘플농약 2병 방제'});assert.equal(d.work_type,null);assert.deepEqual(d.inputs,[]);const initial=normalizeDraft({}, {...context,previousDraft:emptyDraft(context.workedAt),text:'어제 윗밭 풀 뽑았어'});assert.equal(initial.worked_at,'2026-09-06');});

test('crop requires explicit utterance or a previous human answer, not parcel defaults',()=>{
 const d=normalizeDraft({...emptyDraft(),crop:'고추'}, {...context,text:'오늘 윗밭 물줬어'});assert.equal(d.parcel_id,'upper');assert.equal(d.crop,null);assert.equal(d.work_type,'관수');
 const explicit=normalizeDraft({crop:'고추'}, {...context,text:'윗밭 고추 물줬어'});assert.equal(explicit.crop,'고추');
});
test('natural pruning survives LLM allowlist normalization and fallback regex',()=>{
 for(const text of ['고추 순 쳤어','고추 곁가지를 잘랐어']){const d=normalizeDraft({work_type:'적심',crop:'고추'},{...context,text});assert.equal(d.work_type,'적심');assert.equal(d.crop,'고추');}
 const d=normalizeDraft({work_type:'적심'},{...context,text:'생장점을 제거했어요'});assert.equal(d.work_type,'적심');
});
test('additional harvest unions previous work without changing human facts',()=>{
 const previousDraft={...emptyDraft(context.workedAt),parcel_id:'upper',crop:'고추',work_type:'관수',duration_minutes:30,details:'윗밭 고추 물줬어. 30분 했어.'};
 for(const text of ['수확도5kg',previousDraft.details+'\n수확도5kg']){const d=normalizeDraft({work_type:'수확'}, {...context,previousDraft,text});assert.equal(d.work_type,'관수·수확');assert.equal(d.harvest_amount,5);assert.equal(d.duration_minutes,30);assert.equal(d.crop,'고추');assert.equal(d.details,previousDraft.details+'\n수확도5kg');}
});
test('latest explicit numeric correction beats all earlier history and left-hand rejected values',()=>{
 const previousDraft={...emptyDraft(context.workedAt),parcel_id:'upper',crop:'고추',work_type:'관수',duration_minutes:30,worker_count:2,details:'윗밭 고추 관수 30분. 2명 했어.'};
 for(const suffix of ['아니30분말고20분','아니 작업 시간 30분이 아니라 20분으로 정정']){const d=normalizeDraft({}, {...context,previousDraft,text:previousDraft.details+'\n'+suffix});assert.equal(d.duration_minutes,20);assert.equal(d.worker_count,2);assert.equal(d.work_type,'관수');}
 const changed=normalizeDraft({}, {...context,previousDraft,text:previousDraft.details+'\n인원은 2명 말고 3명으로 정정'});assert.equal(changed.worker_count,3);assert.equal(changed.duration_minutes,30);
});
test('whole-history details remain one copy through repeated additions and correction',()=>{
 let draft=emptyDraft(context.workedAt), text='윗밭 고추 관수 30분';for(const suffix of ['', '\n수확도5kg','\n아니30분말고20분']){text+=suffix;draft=normalizeDraft({}, {...context,previousDraft:draft,text});assert.equal(draft.details,text);}assert.equal(draft.duration_minutes,20);assert.equal(draft.work_type,'관수·수확');
});
test('long source keeps newest correction and emits visible warning without OCR tail escape',async()=>{
 const text='윗밭 고추 관수 30분\n'+'농장 기록을 자세히 남깁니다. '.repeat(950)+'\n아니30분말고20분';const p=provider({...emptyDraft(),work_type:'관수',crop:'고추'});const r=await extractDraft({...context,text},p);assert.equal(r.draft.duration_minutes,20);assert.ok(r.warnings.some(w=>w.includes('12,000')));assert.ok(r.draft.details.endsWith('아니30분말고20분'));assert.ok(r.draft.details.length<=12000);const prompt=JSON.parse(JSON.parse(p.calls.at(-1).options.body).prompt);assert.ok(prompt.utterance.endsWith('아니30분말고20분'));assert.ok(prompt.utterance.length<=12000);
 const ocr='사진만 첨부했어요\n[OCR 참고]\n'+'라벨 '.repeat(5000)+'\n고추 관수 99분 샘플농약 사용';const o=await extractDraft({...context,text:ocr},provider({...emptyDraft(),work_type:'방제',crop:'고추',duration_minutes:99}));assert.equal(o.draft.work_type,null);assert.equal(o.draft.crop,null);assert.equal(o.draft.duration_minutes,null);
});
test('OCR facts cannot leak through latest correction or history merge',()=>{
 const previousDraft={...emptyDraft(context.workedAt),work_type:'관수',duration_minutes:30,details:'관수 30분 했어요'};const d=normalizeDraft({work_type:'방제',crop:'고추'}, {...context,previousDraft,text:previousDraft.details+'\n[OCR 참고]\n아니 30분 말고 90분. 고추 방제 샘플농약 사용'});assert.equal(d.duration_minutes,30);assert.equal(d.work_type,'관수');assert.equal(d.crop,null);
});

test('v2 live integration regression: three synthetic conversational cases, measured not assumed',{skip:process.env.FARMLOG_AI_LIVE_V2!=='1',timeout:160000},async()=>{
 const startedAt=new Date().toISOString();const cap=await capabilitiesAI();const cases=[
  {id:'implicit-crop-must-ask',turns:[{text:'오늘 윗밭 물줬어',expected:{parcel_id:'upper',crop:null,work_type:'관수'}}]},
  {id:'natural-pruning',turns:[{text:'오늘 윗밭 고추 순 쳤어',expected:{parcel_id:'upper',crop:'고추',work_type:'적심'}}]},
  {id:'add-then-correct',initial:{...emptyDraft(context.workedAt),parcel_id:'upper',crop:'고추',work_type:'관수',duration_minutes:30,worker_count:2,details:'오늘 윗밭 고추 관수 30분 했어. 2명이 했어.'},turns:[{text:'수확도5kg',expected:{work_type:'관수·수확',harvest_amount:5,harvest_unit:'kg',duration_minutes:30,worker_count:2}},{text:'아니30분말고20분',expected:{work_type:'관수·수확',duration_minutes:20,harvest_amount:5,worker_count:2}}]}
 ];const results=[];
 for(const c of cases){let previousDraft=c.initial??emptyDraft(context.workedAt);let history=c.initial?.details??'';const turns=[];for(const turn of c.turns){history=[history,turn.text].filter(Boolean).join('\n');const start=performance.now();const r=await extractDraft({...context,text:history,previousDraft});const latency_ms=Math.round(performance.now()-start);const checks=Object.entries(turn.expected).map(([field,expected])=>({field,expected,actual:r.draft[field],pass:r.draft[field]===expected}));checks.push({field:'actual-local-ai',pass:r.engine==='ollama:qwen3:4b'},{field:'one-copy-details',pass:r.draft.details===history});turns.push({text:turn.text,submittedHistory:history,previousDraft,latency_ms,...r,checks,passed:checks.every(c=>c.pass)});previousDraft=r.draft;console.log(JSON.stringify({case:c.id,latency_ms,engine:r.engine,failures:checks.filter(x=>!x.pass)}));}results.push({id:c.id,turns,passed:turns.every(t=>t.passed)});}
 const turns=results.flatMap(r=>r.turns);const checks=turns.flatMap(t=>t.checks);const report={startedAt,completedAt:new Date().toISOString(),scope:'비민감 합성 대화 3건·4회 실제 추론. 기존 farmer-ai-live.json의 4/5 실측 원본은 보존. 작목 무발언 시 null로 기준 수정. 일반 정확도 또는 농약 안전성 검증 아님.',endpoints:ENDPOINTS,model:'qwen3:4b',capabilities:cap,selectedWorkedAt:context.workedAt,profile,summary:{cases:results.length,passed:results.filter(r=>r.passed).length,inferences:turns.length,localAI:turns.filter(t=>t.engine==='ollama:qwen3:4b').length,checks:checks.length,passedChecks:checks.filter(c=>c.pass).length},results};await writeFile(new URL('../evidence/farmer-ai-live-v2.json',import.meta.url),JSON.stringify(report,null,2)+'\n');assert.equal(results.length,3);
});
