import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const read=name=>readFile(new URL(`../src/farmer/${name}`,import.meta.url),'utf8');
const [app,html,css,sw,manifest]=await Promise.all(['app.js','index.html','style.css','sw.js','manifest.webmanifest'].map(read));
const escapeSource=app.slice(app.indexOf('const esc ='),app.indexOf('const icon ='));
function escape(value){return vm.runInNewContext(escapeSource+'esc(value)',{value});}
test('farmer UI escapes all untrusted string delimiters',()=>{assert.equal(escape('<script a="x">&\'🙂'),'&lt;script a=&quot;x&quot;&gt;&amp;&#39;🙂');assert.equal(escape(null),'');});
test('phone centered layout, readable base, accessible minimum targets',()=>{assert.match(css,/max-width:520px;margin:0 auto/);assert.match(css,/font-size:18px/);assert.match(css,/min-height:56px/);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion/);});
test('shell has no duplicate IDs or remote asset dependencies',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);assert.doesNotMatch(html,/(?:src|href)="https?:\/\//);assert.match(html,/capture="environment"/);assert.match(html,/aria-live="polite"/);assert.doesNotMatch(html,/\p{Extended_Pictographic}/u);});
test('PWA local scope and shell-only caching exclude API and media',()=>{const m=JSON.parse(manifest);assert.equal(m.display,'standalone');assert.equal(m.scope,'./');assert.match(sw,/url.pathname.includes\('\/api\/'\)/);assert.match(sw,/allowed.includes\(url.pathname\)/);assert.doesNotMatch(sw,/cache\.put\([^)]*api/);});
test('one-click local recording without cloud speech or hold gesture',()=>{assert.match(app,/getUserMedia\(\{audio:true\}\)/);assert.match(app,/new MediaRecorder/);assert.match(app,/if\(state.recording\)\{recorder.stop\(\)/);assert.doesNotMatch(app,/SpeechRecognition|webkitSpeech|pointerdown|touchstart/);assert.match(app,/getTracks\(\).forEach\(t=>t.stop\(\)\)/);});
test('explicit consent, IndexedDB blobs, retry and no auto-send example',()=>{assert.match(html,/id="consent"/);assert.match(app,/indexedDB.open/);assert.match(app,/files:state.files/);assert.match(app,/data-retry/);const example=app.slice(app.indexOf("sample:()=>"),app.indexOf('send:()=>'));assert.match(example,/state.text=/);assert.doesNotMatch(example,/api\(|send\(/);});
test('draft table separates purchase/use and never fills unknown with zero',()=>{const source=app.slice(app.indexOf('function diary('),app.indexOf('function chat('));const d={worked_at:'2026-09-07',parcel_id:'p1',crop:'토마토',work_type:'관수',details:'<img src=x onerror=alert(1)>',inputs:[{action:'purchase',kind:'fertilizer',name:'비료',quantity:2,unit:'포',dilution:null}],area_m2:null,worker_count:null,duration_minutes:30,harvest_amount:null};const output=vm.runInNewContext(escapeSource+source+'diary(d)',{d,state:{boot:{profile:{parcels:[{id:'p1',name:'윗밭'}]}}}});assert.match(output,/자재 구입/);assert.match(output,/자재 사용/);assert.match(output,/미기재/);assert.match(output,/30 분/);assert.doesNotMatch(output,/0 명|0 ㎡|<img src=x/);assert.match(output,/&lt;img/);});
test('media is awaited and its accepted ID saved before session creation',async()=>{const order=[];const state={};const job={id:'job-1',text:'오늘 작업',workedAt:'2026-09-07',files:[{kind:'audio',blob:'test-blob'}]};const source=app.slice(app.indexOf('async function sendJob('),app.indexOf('async function send('));const context={state,job,notice:()=>{},uploadFile:async()=>{await Promise.resolve();order.push('media-complete');return{id:'media-1',processing:'unavailable'};},put:async()=>order.push('checkpoint'),api:async(path,body)=>{order.push('session');assert.deepEqual(Array.from(body.attachmentIds),['media-1']);return{id:'session-1',draft:{worked_at:'2026-09-07'}};},remove:async()=>order.push('remove'),refreshQueue:async()=>{},saveComposer:async()=>{},bootstrap:async()=>{}};await vm.runInNewContext(source+'sendJob(job)',context);assert.deepEqual(order,['media-complete','checkpoint','session','remove']);assert.equal(state.view,'chat');});
test('all manual quantity fields and final reviewed confirmation are present',()=>{for(const key of ['inputs','dilution','harvest_amount','harvest_unit','duration_minutes','worker_count','area_m2'])assert.ok(app.includes(key));assert.match(app,/idempotencyKey:id/);assert.match(app,/if\(!state.reviewed\)/);assert.match(app,/sessions\/\$\{encodeURIComponent\(state.session.id\)\}\/draft/);});
test('print uses returned saved HTML in same-origin sandbox without script permission',()=>{assert.match(app,/parseFromString\(r.html,'text\/html'\)/);assert.match(app,/allow-same-origin allow-modals/);assert.doesNotMatch(app,/allow-scripts/);assert.match(app,/iframe.contentWindow.print\(\)/);assert.match(app,/new Blob\(\[r.csv\]/);});
