import {speechAvailability,transcribeLocal,cancelLocalSpeech} from './speech-local.js';
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const state = {view:'home',boot:null,session:null,entry:null,history:[],text:'',workedAt:today(),files:[],queue:[],busy:false,recording:false,speechBusy:false,browserSpeech:null,filters:{from:today().slice(0,8)+'01',to:today(),parcel_id:''},editor:null,reviewed:false};
let database, recorder, stream, timer, fileUrls = [];
function notice(text='') { $('#notice').textContent=text; }
async function api(path, body) {
  const response = await fetch(`/api/app/${path}`, {method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || `요청 실패 (${response.status})`);
  return data;
}
function dbOpen() { return new Promise((resolve,reject)=>{const req=indexedDB.open('farm-log-farmer',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);}); }
function store(mode, operation) { return new Promise((resolve,reject)=>{if(!database)return reject(new Error('브라우저 임시보관을 사용할 수 없어요.'));const tx=database.transaction('drafts',mode);const req=operation(tx.objectStore('drafts'));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}); }
const put = item => store('readwrite',s=>s.put(item));
const remove = id => store('readwrite',s=>s.delete(id));
async function saveComposer() { if(!database)return; await put({id:'composer',text:state.text,workedAt:state.workedAt,files:state.files,sessionId:state.session?.id || null,updatedAt:Date.now()}); }
function persist() { saveComposer().catch(e=>notice(e.message)); }
async function refreshQueue() {if(database)state.queue=(await store('readonly',s=>s.getAll())).filter(x=>x.id!=='composer');}
async function bootstrap() {try{state.boot=await api('bootstrap');state.browserSpeech=await speechAvailability();state.boot.capabilities.stt={...state.browserSpeech,model:state.browserSpeech.engine};$('#connection').textContent='로컬 연결됨';}catch(e){$('#connection').textContent='연결 안 됨';notice(`로컬 서버(8880)에 연결하지 못했어요. 입력은 임시보관하고 연결 후 다시 보내세요. ${e.message}`);} }
function parcelOptions(selected, blank=true) {return `${blank?'<option value="">필지 선택</option>':''}${(state.boot?.profile.parcels || []).map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}`;}
function engineTag(session) {return `<span class="tag">${esc(session?.engine || (state.boot?.capabilities.llm.available?state.boot.capabilities.llm.model:'AI 연결 확인 필요'))}</span>`;}
function mediaCards(items, local=false) {return items.map((m,i)=>{let url=m.url;if(local){url=URL.createObjectURL(m.blob);fileUrls.push(url);}else if(!/^\/api\/app\/media\/[a-zA-Z0-9-]+$/.test(url || ''))url='';return `<div class="card media">${m.kind==='photo'?`<img src="${esc(url)}" alt="첨부한 농사 사진" loading="lazy">`:`<audio src="${esc(url)}" controls preload="metadata"></audio>`}<p>${local?`${m.kind==='photo'?'사진':'음성'} · 전송 전`:m.kind==='audio'?'음성 원문 확인':'사진에서 읽은 글'}</p>${!local?`<details><summary>인식한 원문 확인</summary><p class="${m.processing==='ready'?'':'warn'}">${esc(m.transcriptCandidate || m.transcript || m.ocrText || (m.kind==='audio'?'자동 음성인식 불가 · 직접 글로 보완해 주세요.':'자동으로 읽은 글이 없어요. 작업 내용을 직접 알려주세요.'))}</p><small>${esc(m.detail || '')}</small>${m.kind==='audio'?'<p class="caption">음성 원문이 다르면 아래 대화창에 올바른 내용을 적어주세요.</p>':''}</details>`:`<button data-remove-file="${i}">첨부 빼기</button>`}</div>`;}).join('');}
function composer() {return `<div class="section"><label for="worked-at">작업한 날짜</label><input id="worked-at" type="date" value="${esc(state.workedAt)}"><label for="message">${state.view==='chat'?'덧붙이거나 바로잡을 내용을 적어요':'어떤 농사일을 하셨나요?'}</label><textarea id="message" placeholder="예: 오늘 3번 하우스 토마토에 30분 물 주고 곁순을 땄어">${esc(state.text)}</textarea><div class="row"><button data-action="photo" ${state.busy?'disabled':''}>${icon('camera')}사진 첨부</button><button data-action="sample">예시 채우기</button></div><div class="section">${mediaCards(state.files,true)}</div><button class="primary" data-action="send" ${state.busy?'disabled':''}>${state.busy?'처리 중 · 입력은 보관돼요':state.view==='chat'?'대화 보내기':'이 내용으로 일지 시작'}</button><p class="caption section">${state.view==='chat'?'추가 사진·음성은 새 기록에서 첨부할 수 있어요.':'인식한 글은 틀릴 수 있어요. 확인·수정한 뒤 보내세요. 입력은 이 브라우저에 임시보관해요.'}</p></div>`;}
function home() {return `<section class="hero"><p class="eyebrow">${esc(state.boot?.profile.farm_name || '나의 농장')}</p><h1>오늘 농사,<br>말로 남겨요.</h1><p>말하고, 사진을 붙이고,<br>함께 확인하면 영농일지가 돼요.</p><button class="mic ${state.recording?'recording':''}" data-action="mic" aria-pressed="${state.recording}" ${state.busy?'disabled':''}>${icon('mic')}<span>${state.recording?'녹음 마치기':'눌러서 말하기'}</span><small>${state.recording?'한 번 더 누르면 녹음이 끝나요':'한 번 눌러 시작, 다시 눌러 종료'}</small></button><div class="row section"><button data-action="photo">${icon('camera')}사진으로</button><button data-action="write">${icon('chat')}글로 적기</button></div><button class="plain section" data-action="audio-file">녹음 파일 불러오기</button>${state.speechBusy?'<button class="plain section" data-action="cancel-speech">음성 인식 취소</button>':''}</section>${composer()}${state.queue.length?`<section class="section"><h2>보내지 못한 기록 ${state.queue.length}개</h2>${state.queue.map(q=>`<div class="card"><p>${esc(q.text || '사진·음성 기록')}</p><small>${esc(q.workedAt)} · 첨부 ${q.files?.length || 0}개</small><button data-retry="${esc(q.id)}" ${state.busy?'disabled':''}>다시 보내기</button></div>`).join('')}</section>`:''}<section class="section"><h2>이어서 쓰기</h2>${state.session?`<button class="entry" data-action="resume-current">작성하던 대화 계속하기</button>`:''}${(state.boot?.pending || []).map(s=>`<button class="entry" data-session="${esc(s.id)}"><strong>${esc(typeof s.preview==='string'?s.preview:'작성 중인 영농일지')}</strong><small>임시보관 · 눌러서 이어 쓰기</small></button>`).join('') || (!state.session?'<p class="empty">작성 중인 일지가 없어요.</p>':'')}</section><section class="section"><h2>최근 영농일지</h2>${entryList((state.boot?.entries || []).slice(0,3))}</section><p class="caption section">기록은 로컬 기기에 보관돼요. 비민감 시험 입력만 사용해 주세요.</p>`;}
function entryList(entries) {return entries.length?`<div class="stack">${entries.map(e=>`<button class="entry" data-entry="${esc(e.id)}"><small>${esc(e.worked_at)} · ${esc(e.parcel_name)}</small><strong>${esc(e.crop)} · ${esc(e.work_type)}</strong></button>`).join('')}</div>`:'<p class="empty">아직 저장된 영농일지가 없어요.<br>오늘 한 일을 남겨볼까요?</p>';}
function diary(d, entry=false) {const name=d.parcel_name || state.boot?.profile.parcels.find(p=>p.id===d.parcel_id)?.name;const val=x=>x===null||x===undefined||x===''?'미기재':esc(x);const rows=[['작업일',d.worked_at],['필지',name],['작목',d.crop],['날씨',d.weather],['작업단계',d.work_type],['작업면적',d.area_m2==null?null:`${d.area_m2} ㎡`],['작업인원',d.worker_count==null?null:`${d.worker_count} 명`],['작업시간',d.duration_minutes==null?null:`${d.duration_minutes} 분`],['수확량',d.harvest_amount==null?null:`${d.harvest_amount} ${d.harvest_unit || '(단위 미기재)'}`]];return `<article class="diary"><small>${entry?'확인하고 저장한 기록':'저장 전 · 확인용 초안'}</small><h2>영농일지</h2><p class="caption">정부 작성예시 항목을 반영한 FarmLog 영농일지</p><table><tbody>${rows.map(([k,v])=>`<tr><th>${k}</th><td>${val(v)}</td></tr>`).join('')}${['purchase','use'].map(a=>`<tr><th>자재 ${a==='purchase'?'구입':'사용'}</th><td>${(d.inputs || []).filter(i=>i.action===a).map(i=>`${esc(({pesticide:'농약',fertilizer:'비료',seed:'종자',other:'기타'})[i.kind])} · ${val(i.name)}<br>${val(i.quantity)} ${val(i.unit)}${i.dilution?` / 희석 ${esc(i.dilution)}`:''}`).join('<hr>') || '미기재'}</td></tr>`).join('')}</tbody></table><h3 class="section">세부 작업내용</h3><p class="details">${val(d.details)}</p><small>공식 고정 서식이나 인증 심사 통과를 보장하지 않아요.</small></article>`;}
function chat() {const s=state.session;return `<button class="back" data-nav="home">홈으로</button><div class="row"><h1>함께 일지 쓰기</h1>${engineTag(s)}</div>${s.supersedes?'<p class="warn">기존 기록을 정정하고 있어요. 저장하면 이전 기록과 연결돼요.</p>':''}${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}">${esc(m.text)}</div>`).join('')}${mediaCards(s.attachments || [])}${(s.warnings || []).length?`<details><summary>처리 안내 확인</summary>${s.warnings.map(w=>`<p class="warn">${esc(w)}</p>`).join('')}</details>`:''}${s.question?`<section class="question"><h2>${esc(s.question.text)}</h2><div class="options">${s.question.options.map((o,i)=>`<button data-option="${i}" ${state.busy?'disabled':''}>${esc(o.label)}</button>`).join('')}</div><button class="plain section" data-action="skip">지금은 모르겠어요</button></section>`:!s.ready?'<p class="warn">확인화면에서 빠진 항목을 채우거나 나중에 이어 쓰세요.</p>':''}${composer()}<details><summary>지금까지 정리한 초안</summary>${diary(s.draft)}</details><button class="primary" data-action="preview" ${state.busy?'disabled':''}>영농일지로 만들기</button><button class="plain section" data-action="keep">임시보관하고 홈으로</button>`;}
const fields=[['worked_at','작업일','date'],['parcel_id','필지','parcel'],['crop','작목','text'],['work_type','작업단계','text'],['weather','날씨','text'],['area_m2','작업면적 (㎡)','number'],['worker_count','작업인원 (명)','number'],['duration_minutes','작업시간 (분)','number'],['harvest_amount','수확량','number'],['harvest_unit','수확 단위','text']];
function editor(d) {return `<form id="draft-form"><p>작업일·필지·작목·작업단계는 꼭 확인해 주세요. 모르는 수량은 비워두세요.</p>${fields.map(([k,l,t])=>`<label for="f-${k}">${l}${['worked_at','parcel_id','crop','work_type'].includes(k)?' *':''}</label>${t==='parcel'?`<select id="f-${k}" name="${k}" required>${parcelOptions(d[k])}</select>`:`<input id="f-${k}" name="${k}" type="${t}" ${t==='number'?'min="0" step="any"':''} value="${esc(d[k])}" ${['worked_at','crop','work_type'].includes(k)?'required':''}>`}`).join('')}<label for="f-details">세부 작업내용</label><textarea id="f-details" name="details">${esc(d.details)}</textarea><h3 class="section">구입·사용한 자재</h3>${(d.inputs || []).map((i,n)=>`<fieldset class="fieldgroup"><legend>자재 ${n+1}</legend><label>구입 또는 사용<select name="input-${n}-action"><option value="use" ${i.action==='use'?'selected':''}>사용</option><option value="purchase" ${i.action==='purchase'?'selected':''}>구입</option></select></label><label>종류<select name="input-${n}-kind">${Object.entries({pesticide:'농약',fertilizer:'비료',seed:'종자',other:'기타'}).map(([v,l])=>`<option value="${v}" ${i.kind===v?'selected':''}>${l}</option>`).join('')}</select></label>${[['name','제품명'],['quantity','수량'],['unit','단위'],['dilution','희석배수']].map(([k,l])=>`<label>${l}<input name="input-${n}-${k}" value="${esc(i[k])}" ${k==='quantity'?'type="number" min="0" step="any"':''}></label>`).join('')}<button type="button" data-remove-input="${n}">이 자재 항목 빼기</button></fieldset>`).join('')}<button type="button" data-action="add-input">자재 항목 추가</button><button type="submit" class="primary section" ${state.busy?'disabled':''}>수정한 내용 반영</button></form>`;}
function preview() {return `<button class="back" data-action="chat">대화로 돌아가기</button><h1>일지를 확인해 주세요</h1>${state.editor?editor(state.editor):`${diary(state.session.draft)}<button class="section" data-action="edit">내용 직접 수정하기</button><label class="check"><input id="reviewed" type="checkbox" ${state.reviewed?'checked':''}>작성 내용과 첨부 원문을 확인했어요.</label><button class="primary section" data-action="confirm" ${!state.reviewed||state.busy?'disabled':''}>${state.busy?'저장 중':'확인하고 저장'}</button>`}`;}
function historyView() {return `<h1>나의 영농일지</h1><form id="filter-form"><div class="row"><label>시작일<input name="from" type="date" value="${esc(state.filters.from)}"></label><label>종료일<input name="to" type="date" value="${esc(state.filters.to)}"></label></div><label>필지<select name="parcel_id">${parcelOptions(state.filters.parcel_id).replace('필지 선택','모든 필지')}</select></label><button type="submit" class="primary section">이 기간 조회</button></form><div class="row section"><button data-export="print">A4 인쇄 / PDF</button><button data-export="csv">CSV 받기</button></div><p class="caption section">확인하고 저장한 최신 기록만 출력해요.</p><div class="section">${entryList(state.history)}</div>`;}
function detail() {return `<button class="back" data-nav="history">목록으로</button>${diary(state.entry,true)}<details><summary>원문과 첨부 확인</summary><p class="bubble">${esc(state.entry.source_text)}</p>${mediaCards(state.entry.attachments || [])}${engineTag(state.entry)}</details>${state.entryHistory?.length?`<details><summary>정정 이력 ${state.entryHistory.length}건</summary>${state.entryHistory.map(e=>`<p>${esc(e.created_at)} · ${esc(e.work_type)}<br>${esc(e.details)}</p>`).join('')}</details>`:''}<button class="primary section" data-action="correct">이 기록 정정하기</button>`;}
function settings() {const p=state.boot?.profile;if(!p)return '<h1>내 농장</h1><p>서버 연결 후 설정할 수 있어요.</p><button data-action="reload">다시 연결</button>';return `<h1>내 농장</h1><p class="muted">처음 보이는 ‘3번 하우스·윗밭’은 예시 설정이에요. 내 시험용 필지 이름과 작목으로 바꿔주세요.</p><form id="profile-form"><label>농장 이름<input name="farm_name" value="${esc(p.farm_name)}" required></label>${p.parcels.map((p,i)=>`<fieldset class="fieldgroup"><legend>필지 ${i+1}</legend><label>필지 이름<input name="parcel-${i}-name" value="${esc(p.name)}" required></label><label>부르는 이름 (쉼표로 구분)<input name="parcel-${i}-aliases" value="${esc(p.aliases.join(', '))}"></label><label>작목<input name="parcel-${i}-crop" value="${esc(p.crop)}"></label><label>면적 (㎡)<input name="parcel-${i}-area_m2" type="number" min="0" step="any" value="${esc(p.area_m2)}"></label></fieldset>`).join('')}<button class="primary" type="submit">농장 설정 저장</button></form><details><summary>로컬 처리 상태</summary>${Object.entries(state.boot.capabilities).map(([k,v])=>`<p><strong>${esc(k.toUpperCase())}</strong> · ${v.available?'사용 가능':'사용 불가'}<br><small>${esc(v.model || '')} ${esc(v.detail)}</small></p>`).join('')}<button data-action="reload">상태 다시 확인</button></details><p class="caption">미전송 입력은 이 브라우저 IndexedDB에, 전송한 원문과 미디어는 로컬 서버에 남아요. 앱 shell만 오프라인 캐시하며 기록 응답은 캐시하지 않아요.</p><a class="button plain" href="http://127.0.0.1:8878/" target="_blank" rel="noopener">사업 구상 / 검증실 (관리자)</a>`;}
function render() {fileUrls.forEach(URL.revokeObjectURL);fileUrls=[];$('#main').innerHTML=({home,chat,preview,history:historyView,detail,settings}[state.view] || home)();document.querySelectorAll('[data-nav]').forEach(b=>b.setAttribute('aria-current',b.dataset.nav===state.view?'page':'false'));}
async function navigate(view) {if(state.recording){notice('먼저 녹음을 마쳐주세요.');return;}if(state.busy)return;await saveComposer();state.view=view;if(view==='history')await loadHistory();render();window.scrollTo(0,0);}
async function loadHistory() {const q=new URLSearchParams(Object.entries(state.filters).filter(([,v])=>v));const r=await api(`entries?${q}`);state.history=r.entries;}
async function busy(fn) {if(state.busy)return;state.busy=true;render();try{await fn();}catch(e){notice(e.message);}finally{state.busy=false;render();}}
function readBase64(blob) {return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
async function uploadFile(file) {if(file.media)return file.media;const r=await api('media',{kind:file.kind,mime:file.blob.type,base64:await readBase64(file.blob),...(file.transcriptCandidate?{transcriptCandidate:file.transcriptCandidate,transcriptEngine:file.transcriptEngine}:{})});return r.media;}
async function sendJob(job) {
  if(job.sessionId) {const s=await api(`sessions/${encodeURIComponent(job.sessionId)}/messages`,{text:job.text,...(job.answerField?{answerField:job.answerField}:{})});state.session=s;}
  else {const attachmentIds=[];for(let i=0;i<job.files.length;i++){notice(`첨부 ${i+1}/${job.files.length} 처리 중이에요. 완료 후 대화를 시작해요.`);job.files[i].media=await uploadFile(job.files[i]);await put(job);attachmentIds.push(job.files[i].media.id);}state.session=await api('sessions',{text:job.text,workedAt:job.workedAt,attachmentIds});}
  await remove(job.id);await refreshQueue();state.view='chat';state.workedAt=state.session.draft.worked_at || state.workedAt;await saveComposer();await bootstrap();notice('내용을 정리했어요. 원문과 빠진 항목을 확인해 주세요.');
}
async function send(text=state.text,answerField) {if(state.recording)throw new Error('녹음을 마친 다음 보내주세요.');if(state.files.length>10)throw new Error('첨부는 한 기록에 최대 10개예요.');if(!state.workedAt)throw new Error('작업 날짜를 선택해 주세요.');if(!text.trim()&&!state.files.length)throw new Error('말·사진·글 중 하나를 남겨주세요.');if(state.view==='chat'&&state.files.length)throw new Error('추가 첨부는 새 기록에서 보내주세요.');const job={id:crypto.randomUUID(),text,workedAt:state.workedAt,files:state.files,sessionId:state.view==='chat'?state.session?.id || null:null,answerField,updatedAt:Date.now()};await put(job);state.text='';state.files=[];await saveComposer();await refreshQueue();try{await sendJob(job);}catch(e){state.view='home';throw new Error(`${e.message} 미전송함에 보관했어요. 다시 보내기를 눌러주세요.`);}}
async function prepareAudio(file) {
 state.speechBusy=true;
 try{await busy(async()=>{const available=state.browserSpeech??await speechAvailability();if(!available.available)throw new Error('로컬 음성 모델을 사용할 수 없어요. 녹음은 보관했으니 글로 보완해 주세요.');const r=await transcribeLocal(file.blob,p=>notice(p.status==='transcribing'?'말을 글로 바꾸고 있어요. 잠시 기다려 주세요.':'로컬 음성 모델을 준비하고 있어요. 외부 전송은 없어요.'));if(!r.text.trim())throw new Error('인식된 글이 없어요. 원본은 보관했으니 직접 적어주세요.');file.transcriptCandidate=r.text;file.transcriptEngine=r.engine;state.text=(state.text?state.text+'\n':'')+r.text;await saveComposer();notice('말을 글로 바꿨어요. 틀린 부분을 고친 뒤 일지를 시작해 주세요.');});}finally{state.speechBusy=false;render();}
}
async function startMic() {
  if(state.view==='chat')throw new Error('음성 첨부는 홈의 새 기록에서 시작해 주세요.');
  if(state.recording){recorder.stop();return;}
  if(!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder)throw new Error('이 브라우저에서 녹음할 수 없어요. localhost의 지원 브라우저를 사용하거나 글로 적어주세요.');
  stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];
  const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));
  try{recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});}catch(e){stream.getTracks().forEach(t=>t.stop());throw e;}
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onstop=async()=>{clearTimeout(timer);stream.getTracks().forEach(t=>t.stop());state.recording=false;const blob=new Blob(chunks,{type:recorder.mimeType.split(';')[0]});if(blob.size>16*1024*1024)notice('음성이 16MB를 넘어요. 더 짧게 녹음해 주세요.');else if(blob.size){const file={kind:'audio',blob};state.files.push(file);try{await saveComposer();await prepareAudio(file);}catch(e){notice(e.message);}}render();};
  recorder.onerror=e=>{notice(`녹음 오류: ${e.error?.message || '다시 시도해 주세요.'}`);if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());state.recording=false;render();};
  recorder.start(1000);state.recording=true;timer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},180000);render();notice('녹음 중이에요. 종료 버튼을 눌러주세요. 최대 3분 뒤 자동 종료돼요.');
}
function readDraftForm() {const f=new FormData($('#draft-form'));const d=structuredClone(state.editor);for(const [k,,t]of fields){const v=String(f.get(k) || '').trim();d[k]=v===''?null:t==='number'?Number(v):v;}d.details=String(f.get('details') || '');d.inputs=d.inputs.map((_,n)=>{const i={};for(const k of ['action','kind','name','quantity','unit','dilution']){const v=String(f.get(`input-${n}-${k}`)||'').trim();i[k]=v===''?null:k==='quantity'?Number(v):v;}return i;});return d;}
async function exportFile(kind) {if(!state.history.length)throw new Error('선택한 기간에 저장된 기록이 없어요.');const r=await api('export',{...Object.fromEntries(Object.entries(state.filters).filter(([,v])=>v)),reviewed:true});if(kind==='csv'){const url=URL.createObjectURL(new Blob([r.csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='farm-log.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('CSV 다운로드를 요청했어요.');}else{document.querySelectorAll('.print-frame').forEach(f=>f.remove());const printDoc=new DOMParser().parseFromString(r.html,'text/html');printDoc.querySelectorAll('style,script').forEach(n=>n.remove());const css=printDoc.createElement('link');css.rel='stylesheet';css.href=new URL('./style.css',location.href).href;printDoc.head.append(css);printDoc.querySelectorAll('article').forEach(n=>n.classList.add('diary')); const iframe=document.createElement('iframe');iframe.className='print-frame';iframe.title='영농일지 인쇄 미리보기';iframe.setAttribute('sandbox','allow-same-origin allow-modals');iframe.onload=()=>{iframe.contentWindow.focus();iframe.contentWindow.print();};iframe.srcdoc='<!doctype html>'+printDoc.documentElement.outerHTML;document.body.append(iframe);notice('인쇄 창에서 프린터 또는 PDF 저장을 선택해 주세요.');}}
const actions={
  mic:()=>startMic(),'cancel-speech':()=>cancelLocalSpeech(),'audio-file':()=>$('#audio-input').click(),photo:()=>{if(state.view==='chat')throw new Error('사진을 추가하려면 홈에서 새 기록을 시작해 주세요.');$('#photo-input').click();},write:()=>$('#message')?.focus(),sample:()=>{state.text='오늘 3번 하우스 토마토에 30분 물 주고 곁순을 땄어';persist();render();$('#message')?.focus();},
  send:()=>busy(()=>send()),skip:()=>busy(()=>send('모르겠어요')),
  preview:()=>{state.editor=null;state.reviewed=false;state.view='preview';render();window.scrollTo(0,0);},chat:()=>{state.editor=null;state.view='chat';render();},edit:()=>{state.editor=structuredClone(state.session.draft);state.reviewed=false;render();},
  'add-input':()=>{state.editor=readDraftForm();state.editor.inputs.push({action:'use',kind:'fertilizer',name:null,quantity:null,unit:null,dilution:null});render();},
  confirm:()=>busy(async()=>{if(!state.reviewed)throw new Error('작성 내용 확인에 체크해 주세요.');const key=`farm-log-confirm-${state.session.id}`;let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id);}const r=await api(`sessions/${encodeURIComponent(state.session.id)}/confirm`,{reviewed:true,idempotencyKey:id,...(state.session.supersedes?{supersedes:state.session.supersedes}:{})});state.entry=r.entry;state.entryHistory=[];state.session=null;state.text='';state.files=[];state.view='detail';await saveComposer();await bootstrap();notice(r.duplicate?'이미 저장된 기록을 열었어요.':'영농일지를 저장했어요.');}),
  keep:async()=>{await saveComposer();await bootstrap();state.view='home';render();notice('작성 중인 대화는 서버에, 미전송 입력은 브라우저에 보관했어요.');},
  'resume-current':()=>{state.view='chat';render();},reload:()=>busy(async()=>{await bootstrap();}),
  correct:()=>busy(async()=>{state.session=await api(`entries/${encodeURIComponent(state.entry.id)}/correct`,{});state.view='preview';state.editor=structuredClone(state.session.draft);state.reviewed=false;await saveComposer();})
};
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||b.disabled||(state.busy&&b.dataset.action!=='cancel-speech'))return;try{
 if(b.dataset.nav){await navigate(b.dataset.nav);return;}
 if(b.dataset.action){await actions[b.dataset.action]?.();return;}
 if(b.dataset.session){await busy(async()=>{await saveComposer();state.session=await api(`sessions/${encodeURIComponent(b.dataset.session)}`);state.view='chat';state.workedAt=state.session.draft.worked_at || state.workedAt;await saveComposer();});return;}
 if(b.dataset.entry){await busy(async()=>{const r=await api(`entries/${encodeURIComponent(b.dataset.entry)}`);state.entry=r.entry;state.entryHistory=r.history;state.view='detail';});return;}
 if(b.dataset.option!==undefined){const question=state.session.question;const option=question.options[Number(b.dataset.option)];await busy(()=>send(String(option.value),question.field));return;}
 if(b.dataset.retry){await busy(()=>sendJob(state.queue.find(q=>q.id===b.dataset.retry)));return;}
 if(b.dataset.removeFile!==undefined){state.files.splice(Number(b.dataset.removeFile),1);await saveComposer();render();return;}
 if(b.dataset.removeInput!==undefined){state.editor=readDraftForm();state.editor.inputs.splice(Number(b.dataset.removeInput),1);render();return;}
 if(b.dataset.export){await busy(()=>exportFile(b.dataset.export));}
 }catch(e){notice(e.message);}});
document.addEventListener('input',event=>{if(event.target.id==='message'){state.text=event.target.value;persist();}if(event.target.id==='worked-at'){state.workedAt=event.target.value;persist();}});
document.addEventListener('change',event=>{if(event.target.id==='reviewed'){state.reviewed=event.target.checked;const b=$('[data-action="confirm"]');if(b)b.disabled=!state.reviewed;}});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;try{
 if(form.id==='draft-form'){const draft=readDraftForm();state.editor=draft;await busy(async()=>{state.session=await api(`sessions/${encodeURIComponent(state.session.id)}/draft`,{draft});state.editor=null;state.reviewed=false;notice('수정한 내용을 반영했어요. 양식을 다시 확인해 주세요.');});}
 if(form.id==='filter-form'){state.filters=Object.fromEntries(new FormData(form));await busy(()=>loadHistory());}
 if(form.id==='profile-form'){const f=new FormData(form);const profile={farm_name:String(f.get('farm_name')).trim(),parcels:state.boot.profile.parcels.map((p,i)=>({id:p.id,name:String(f.get(`parcel-${i}-name`)).trim(),aliases:String(f.get(`parcel-${i}-aliases`)).split(',').map(s=>s.trim()).filter(Boolean),crop:String(f.get(`parcel-${i}-crop`)).trim() || null,area_m2:f.get(`parcel-${i}-area_m2`)===''?null:Number(f.get(`parcel-${i}-area_m2`))}))};await busy(async()=>{const r=await api('profile',profile);state.boot.profile=r.profile;notice('농장 설정을 저장했어요. 기존 일지의 필지 이름은 유지돼요.');});}
 }catch(e){notice(e.message);}});
$('#photo-input').addEventListener('change',async event=>{for(const file of event.target.files){if(file.size>8*1024*1024){notice('사진 한 장은 8MB 이하여야 해요. 큰 사진은 첨부하지 않았어요.');continue;}state.files.push({kind:'photo',blob:file});}event.target.value='';try{await saveComposer();}catch(e){notice(e.message);}render();});
$('#audio-input').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>16*1024*1024){notice('음성 파일은 16MB 이하여야 해요.');return;}const item={kind:'audio',blob:file};state.files.push(item);try{await saveComposer();await prepareAudio(item);}catch(e){notice(e.message);}render();});
$('#agree').addEventListener('click',()=>{try{localStorage.setItem('farm-log-local-consent-v1','yes');$('#consent').close();}catch{notice('브라우저 저장소를 허용한 뒤 시작해 주세요.');}});
$('#consent').addEventListener('cancel',e=>e.preventDefault());
window.addEventListener('online',()=>{notice('연결이 돌아왔어요. 미전송함의 다시 보내기를 눌러주세요.');bootstrap().then(render);});
window.addEventListener('offline',()=>{$('#connection').textContent='오프라인';notice('연결이 끊겼어요. 입력은 이 브라우저에 임시보관해요.');});
window.addEventListener('pagehide',()=>{if(stream)stream.getTracks().forEach(t=>t.stop());});
window.addEventListener('beforeunload',event=>{if(state.recording){event.preventDefault();event.returnValue='';}});
$('.brand').addEventListener('click',event=>{event.preventDefault();navigate('home').catch(e=>notice(e.message));});
async function init(){render();try{if(localStorage.getItem('farm-log-local-consent-v1')!=='yes')$('#consent').showModal();}catch{$('#consent').showModal();}try{database=await dbOpen();const saved=await store('readonly',s=>s.get('composer'));if(saved){state.text=saved.text || '';state.workedAt=saved.workedAt || today();state.files=saved.files || [];state.resumeId=saved.sessionId;}await refreshQueue();}catch(e){notice(`임시보관을 사용할 수 없어요: ${e.message}`);}await bootstrap();if(state.resumeId){try{state.session=await api(`sessions/${encodeURIComponent(state.resumeId)}`);}catch{notice('이전 대화를 불러오지 못했어요. 미전송 입력은 남아 있어요.');}}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notice('오프라인 앱 설치는 사용할 수 없어요. 온라인 기록은 계속할 수 있어요.'));}
init();
