import {mkdir,open,readFile,lstat,rename} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
export const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
export const now=()=>new Date().toISOString();
export const workTypes=['파종','정식','관수','시비','방제','제초','적심','수확','출하','자재구매','기타'];
export function dateOK(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
export function object(v){if(!v||typeof v!=='object'||Array.isArray(v))fail('JSON object required');return v;}
export function keys(v,allowed){object(v);if(Object.keys(v).some(k=>!allowed.includes(k)))fail('Unknown field');}
export function string(v,max=200,allowEmpty=false){if(typeof v!=='string'||v.length>max||(!allowEmpty&&!v.trim())||v.includes('\0'))fail('Invalid text');return v;}
const num=(v,max=1e12)=>{if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max))fail('Invalid number');return v;};
export function emptyDraft(workedAt=null){return {worked_at:workedAt,parcel_id:null,crop:null,work_type:null,weather:null,area_m2:null,worker_count:null,duration_minutes:null,inputs:[],harvest_amount:null,harvest_unit:null,details:''};}
export function validateDraft(d,profile){keys(d,Object.keys(emptyDraft()));const out={};for(const k of Object.keys(emptyDraft())){if(!(k in d))fail('Missing draft field: '+k);out[k]=d[k];}
 if(d.worked_at!==null&&!dateOK(d.worked_at))fail('Invalid worked_at');if(d.parcel_id!==null&&!profile.parcels.some(p=>p.id===d.parcel_id))fail('Unknown parcel');
 for(const k of ['crop','weather','harvest_unit'])if(d[k]!==null)string(d[k],200);
 if(d.work_type!==null){string(d.work_type,120);if(d.work_type.split('·').some(v=>!workTypes.includes(v)))fail('Invalid work_type');}
 for(const k of ['area_m2','worker_count','duration_minutes','harvest_amount'])num(d[k]);if(d.worker_count!==null&&!Number.isInteger(d.worker_count))fail('worker_count must be integer');
 if((d.harvest_amount===null)!==(d.harvest_unit===null))fail('Harvest amount and unit must be paired');string(d.details,100000,true);
 if(!Array.isArray(d.inputs)||d.inputs.length>100)fail('Invalid inputs');out.inputs=d.inputs.map(i=>{keys(i,['action','kind','name','quantity','unit','dilution']);if(Object.keys(i).length!==6||!['purchase','use'].includes(i.action)||!['pesticide','fertilizer','seed','other'].includes(i.kind))fail('Invalid input');for(const k of ['name','unit','dilution'])if(i[k]!==null)string(i[k],200);num(i.quantity);if((i.quantity===null)!==(i.unit===null))fail('Input quantity and unit must be paired');return {...i};});return structuredClone(out);
}
export function ready(d){return ['worked_at','parcel_id','crop','work_type'].every(k=>typeof d[k]==='string'&&d[k].trim());}
export const defaultProfile=()=>({farm_name:'나의 농장',parcels:[{id:'house-3',name:'3번 하우스',aliases:['3번집'],crop:'토마토',area_m2:null},{id:'upper-field',name:'윗밭',aliases:[],crop:'고추',area_m2:null}]});
export function validateProfile(p){keys(p,['farm_name','parcels']);string(p.farm_name,80);const nonsensitive=v=>{if(/(?:[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|\b01[016789][- ]?\d{3,4}[- ]?\d{4}\b|\b\d{6}[- ]?[1-4]\d{6}\b)/.test(v))fail('Use non-sensitive farm labels only');};nonsensitive(p.farm_name);if(!Array.isArray(p.parcels)||p.parcels.length>10)fail('At most 10 parcels');const ids=new Set();return {farm_name:p.farm_name,parcels:p.parcels.map(v=>{keys(v,['id','name','aliases','crop','area_m2']);const id=v.id??randomUUID();if(typeof id!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(id)||ids.has(id))fail('Invalid parcel id');ids.add(id);string(v.name,80);if(!Array.isArray(v.aliases)||v.aliases.length>10)fail('Invalid aliases');nonsensitive(v.name);v.aliases.forEach(a=>{string(a,80);nonsensitive(a);});if(v.crop!==null)string(v.crop,80);num(v.area_m2);return {id,name:v.name,aliases:[...v.aliases],crop:v.crop,area_m2:v.area_m2};})};}
export function filteredEntries(state,filters={}){keys(filters,['from','to','parcel_id']);for(const k of ['from','to'])if(filters[k]!==undefined&&!dateOK(filters[k]))fail('Invalid '+k);if(filters.from&&filters.to&&filters.from>filters.to)fail('Invalid date range');if(filters.parcel_id!==undefined)string(filters.parcel_id,80);const replaced=new Set(state.entries.map(e=>e.supersedes).filter(Boolean));return state.entries.filter(e=>!replaced.has(e.id)&&(!filters.from||e.worked_at>=filters.from)&&(!filters.to||e.worked_at<=filters.to)&&(!filters.parcel_id||e.parcel_id===filters.parcel_id)).sort((a,b)=>b.worked_at.localeCompare(a.worked_at)||b.created_at.localeCompare(a.created_at));}
export async function openStore(dataDir){await mkdir(dataDir,{recursive:true,mode:0o700});const lockPath=path.join(dataDir,'.writer.lock');let fd;try{fd=await open(lockPath,'wx',0o600);}catch(e){if(e.code==='EEXIST')throw Object.assign(new Error('Writer lock exists; preserve and inspect manually, never reclaim automatically'),{code:'EWRITERLOCK'});throw e;}
 const identity=await fd.stat();const token=randomUUID();let releasePromise;const close=()=>releasePromise??=(async()=>{const current=await lstat(lockPath);if(current.ino!==identity.ino||current.dev!==identity.dev)throw new Error('Writer lock ownership changed');await rename(lockPath,lockPath+'.released-'+token);})();
 try{await fd.writeFile(JSON.stringify({pid:process.pid,token,created_at:now()}));await fd.sync();await fd.close();let state={profile:defaultProfile(),sessions:{},media:{},entries:[],idempotency:{}};const journal=path.join(dataDir,'journal.jsonl');let raw='';try{raw=await readFile(journal,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}
 if(raw&&!raw.endsWith('\n'))throw new Error('Incomplete journal; preserve and inspect manually');let seq=0;const apply=(s,change)=>{keys(change,['profile','session','media','entry','idempotency']);if(change.profile)s.profile=change.profile;if(change.session)s.sessions[change.session.id]=change.session;if(change.media)s.media[change.media.id]=change.media;if(change.entry)s.entries.push(change.entry);if(change.idempotency)Object.defineProperty(s.idempotency,change.idempotency.key,{value:change.idempotency,enumerable:true,writable:true,configurable:true});};
 for(const line of raw.split('\n').filter(Boolean)){const event=JSON.parse(line);if(event.seq!==++seq||!event.change||!event.at)throw new Error('Invalid journal');apply(state,event.change);}
 let queue=Promise.resolve(),poisoned=false;
 const transact=fn=>{const task=queue.then(async()=>{if(poisoned)fail('Storage failed; restart and inspect',503);const result=await fn(structuredClone(state));if(!result.change)return result.value;const event={seq:seq+1,at:now(),change:result.change};let handle;try{handle=await open(journal,'a',0o600);await handle.writeFile(JSON.stringify(event)+'\n');await handle.sync();}catch(e){poisoned=true;throw e;}finally{await handle?.close();}seq++;apply(state,structuredClone(result.change));return result.value;});queue=task.catch(()=>{});return task;};return {get state(){return structuredClone(state);},transact,async close(){await queue;await close();}};
 }catch(e){await fd.close().catch(()=>{});await close();throw e;}
}
