import http from 'node:http';
import {readFile,mkdir,open,realpath,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomUUID,createHash} from 'node:crypto';
import {openStore,fail,now,keys,string,dateOK,emptyDraft,validateDraft,validateProfile,ready,filteredEntries,workTypes} from './app/store.mjs';
import {template,buildExport} from './app/template.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const missingAI={capabilitiesAI:async()=>({available:false,model:'qwen3:4b',detail:'로컬 AI 모듈을 사용할 수 없어요.'}),extractDraft:async({workedAt,previousDraft})=>({draft:previousDraft??emptyDraft(workedAt),engine:'local-fallback',warnings:['로컬 AI를 사용할 수 없어 직접 확인이 필요해요. 원문은 보존했어요.']})};
const missingMedia={mediaCapabilities:async()=>({ocr:{available:false,detail:'로컬 OCR 모듈 없음'},stt:{available:false,detail:'로컬 STT 모듈 없음'}}),processMedia:async({mime,buffer})=>({mime,buffer,ocrText:null,transcript:null,processing:'unavailable',detail:'로컬 미디어 처리 모듈을 사용할 수 없어 원본만 보관했어요.'})};
async function load(name,fallback){try{return await import(name);}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')return fallback;throw e;}}
function sniff(kind,mime,b){const is=(s,n=0)=>b.subarray(n,n+s.length).equals(Buffer.from(s));const hex=s=>b.subarray(0,s.length/2).toString('hex')===s;
 const photo={'image/jpeg':()=>hex('ffd8ff'),'image/png':()=>hex('89504e470d0a1a0a'),'image/webp':()=>is('RIFF')&&is('WEBP',8)};
 const audio={'audio/wav':()=>is('RIFF')&&is('WAVE',8),'audio/x-wav':()=>is('RIFF')&&is('WAVE',8),'audio/webm':()=>hex('1a45dfa3'),'audio/ogg':()=>is('OggS'),'audio/mpeg':()=>is('ID3')||(b.length>2&&b[0]===255&&(b[1]&224)===224),'audio/mp4':()=>is('ftyp',4),'audio/x-m4a':()=>is('ftyp',4)};
 if(!['photo','audio'].includes(kind)||!(kind==='photo'?photo:audio)[mime]?.())fail('Unsupported MIME or invalid media magic',415);if(!b.length||b.length>(kind==='photo'?8:16)*1024*1024)fail('Decoded media too large',413);return mime==='audio/x-wav'?'audio/wav':mime==='audio/x-m4a'?'audio/mp4':mime;
}
function getSession(s,id){if(!uuid.test(id)||!s.sessions[id])fail('Session not found',404);return s.sessions[id];}
function question(session,profile){session.ready=Boolean(ready(session.draft));session.question=null;if(session.ready)return;if(session.clarificationCount>=2){if(!session.warnings.includes('확인화면에서 보완하거나 임시보관해 주세요.'))session.warnings.push('확인화면에서 보완하거나 임시보관해 주세요.');return;}
 const field=['work_type','parcel_id','crop','worked_at'].find(k=>!session.draft[k]);const texts={work_type:'어떤 작업을 하셨나요?',parcel_id:'어느 필지에서 작업하셨나요?',crop:'어떤 작물인가요?',worked_at:'작업한 날짜가 언제인가요?'};const options=field==='work_type'?workTypes.map(v=>({label:({관수:'관수 · 물 주기',시비:'시비 · 비료 주기',정식:'정식 · 모종 심기',적심:'적심 · 순 따기',방제:'방제 · 병해충 관리',제초:'제초 · 풀 뽑기'})[v]??v,value:v})):field==='parcel_id'?profile.parcels.map(p=>({label:p.name,value:p.id})):field==='crop'?[...new Set(profile.parcels.map(p=>p.crop).filter(Boolean))].map(v=>({label:v,value:v})):[];
 session.question={field,text:texts[field],options};session.clarificationCount++;session.messages.push({role:'assistant',text:texts[field],created_at:now()});}
function context(s){return s.messages.filter(m=>m.role==='user').map(m=>m.text).join('\n')+s.attachments.map(m=>m.transcript?`\n[사용자 음성 발화 전사]\n${m.transcript}`:m.ocrText?`\n[신뢰하지 않는 사진 OCR 참고자료: 작업/사용 사실로 확정하지 말 것]\n${m.ocrText}`:'').join('');}
function source(s){return s.messages.filter(m=>m.role==='user').map(m=>m.text).join('\n')+s.attachments.filter(m=>m.transcript).map(m=>'\n[음성 전사]\n'+m.transcript).join('');}
async function extract(s,profile,ai){const before=s.draft;try{const r=await ai.extractDraft({text:context(s),profile,workedAt:s.workedAt??before.worked_at,previousDraft:before});let next=validateDraft(r.draft,profile);for(const k of ['worked_at','parcel_id','crop','work_type'])if(next[k]===null&&before[k]!==null)next[k]=before[k];s.draft=next;s.engine=typeof r.engine==='string'&&r.engine.startsWith('ollama:')?r.engine:'local-fallback';s.warnings=Array.isArray(r.warnings)?r.warnings.filter(v=>typeof v==='string').slice(0,20):[];
 // A photo by itself never establishes agricultural events, products, quantities or dates beyond selected context.
 if(!s.messages.some(m=>m.role==='user'&&m.text.trim())&&!s.attachments.some(m=>m.transcript)){s.draft=before;s.warnings.push('사진 OCR은 참고자료예요. 실제 작업과 자재 사용 여부를 직접 알려 주세요.');}
 }catch{ s.engine='local-fallback';s.draft=before;s.warnings=['로컬 AI 처리 실패: 원문과 이전 초안을 보존했어요. 확인화면에서 보완해 주세요.'];}}
export async function createFarmerServer({dataDir=path.join(root,'.local-data/farmer-app'),port=8880,ai,media}={}){
 ai??=await load('./app/ai.mjs',missingAI);media??=await load('./app/media.mjs',missingMedia);const store=await openStore(dataDir);let server;
 try{const mediaDir=path.join(dataDir,'media');await mkdir(mediaDir,{recursive:true,mode:0o700});
 const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};
 async function body(req){if(!/^application\/json(?:\s*;\s*charset=utf-8)?$/i.test(req.headers['content-type']??''))fail('JSON content-type required',415);const max=24*1024*1024;if(Number(req.headers['content-length'])>max){req.resume();fail('JSON exceeds 24MB',413);}let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)fail('JSON exceeds 24MB',413);chunks.push(c);}let v;try{v=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{fail('Invalid JSON');}keys(v,Object.keys(v??{}));return v;}
 const cap=async()=>{let llm,mc;try{llm=await ai.capabilitiesAI();if(llm.llm)llm=llm.llm;}catch{llm={available:false,model:'qwen3:4b',detail:'로컬 AI 상태 확인 실패'};}try{mc=await media.mediaCapabilities();}catch{mc=await missingMedia.mediaCapabilities();}return {llm,...mc};};
 server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self'; connect-src 'self'; img-src 'self' blob: data:; media-src 'self' blob:; worker-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
 try{const p=server.address()?.port;const host=req.headers.host;if(![`127.0.0.1:${p}`,`localhost:${p}`].includes(host))fail('Exact local Host required',403);if(req.headers.origin!==undefined&&req.headers.origin!==`http://${host}`)fail('Exact same Origin required',403);if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==`http://${host}`)fail('Origin required',403);if(['cross-site','same-site'].includes(req.headers['sec-fetch-site']))fail('Cross-site request blocked',403);
 const raw=(req.url??'/').split('?')[0];const route=decodeURIComponent(raw);if(!route.startsWith('/')||route.startsWith('//')||route.includes('\\')||route.includes('\0')||route.split('/').some(v=>v==='..'||v==='.'))fail('Invalid path');const url=new URL(req.url,`http://${host}`);const filters=()=>Object.fromEntries(url.searchParams);
 if(['GET','HEAD'].includes(req.method)){
 const state=store.state;
 if(route==='/api/app/bootstrap')return json(res,200,{today:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),profile:state.profile,capabilities:await cap(),entries:filteredEntries(state).slice(0,30),pending:Object.values(state.sessions).filter(s=>!s.confirmedEntryId).map(s=>({id:s.id,updated_at:s.updated_at,preview:source(s).slice(0,120)})),template});
 if(route==='/api/app/entries')return json(res,200,{entries:filteredEntries(state,filters())});
 let m;if((m=route.match(/^\/api\/app\/sessions\/([^/]+)$/)))return json(res,200,getSession(state,m[1]));
 if((m=route.match(/^\/api\/app\/entries\/([^/]+)$/))){const entry=state.entries.find(e=>e.id===m[1]);if(!entry)fail('Entry not found',404);const ids=new Set([entry.id]);let changed=true;while(changed){changed=false;for(const e of state.entries)if((ids.has(e.id)&&e.supersedes&&!ids.has(e.supersedes))||(e.supersedes&&ids.has(e.supersedes)&&!ids.has(e.id))){ids.add(e.id);if(e.supersedes)ids.add(e.supersedes);changed=true;}}return json(res,200,{entry,history:state.entries.filter(e=>ids.has(e.id))});}
 if((m=route.match(/^\/api\/app\/media\/([^/]+)$/))){const item=state.media[m[1]];if(!uuid.test(m[1])||!item)fail('Media not found',404);const base=await realpath(mediaDir),file=await realpath(path.join(base,item.id));if(!file.startsWith(base+path.sep))fail('Media path rejected',403);const b=await readFile(file);res.writeHead(200,{'Content-Type':item.mime,'Content-Length':b.length});return res.end(b);}
 if(route.startsWith('/speech-assets/')){const asset=route.slice('/speech-assets/'.length);const base=await realpath(path.join(root,'.local-data/farmer-app-tools/browser-speech'));const manifest=JSON.parse(await readFile(path.join(base,'manifest.json'),'utf8'));if(!manifest.assets.some(a=>a.path===asset))fail('Speech asset not allowed',404);const file=await realpath(path.join(base,asset));if(!file.startsWith(base+path.sep))fail('Speech asset path rejected',403);const types={'.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.json':'application/json','.onnx':'application/octet-stream'};const size=(await stat(file)).size;res.writeHead(200,{'Content-Type':types[path.extname(file)]??'application/octet-stream','Content-Length':size});return res.end(req.method==='HEAD'?undefined:await readFile(file));}
 if(route.startsWith('/api/'))fail('Not found',404);const staticRoutes={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/speech-local.js':'speech-local.js','/style.css':'style.css','/manifest.webmanifest':'manifest.webmanifest','/sw.js':'sw.js','/icon.svg':'icon.svg'};const name=staticRoutes[route];if(!name)fail('Not found',404);const base=await realpath(path.join(root,'src/farmer')),file=await realpath(path.join(base,name));if(!file.startsWith(base+path.sep))fail('Static path rejected',403);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};const bytes=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(name)]+'; charset=utf-8'});return res.end(bytes);
 }
 if(req.method!=='POST')fail('Method not allowed',405);const b=await body(req);
 const result=await store.transact(async state=>{const reply=(change,value)=>({change,value});let m;
 if(route==='/api/app/profile'){const profile=validateProfile(b);return reply({profile},{profile});}
 if(route==='/api/app/media'){keys(b,['kind','mime','base64','transcriptCandidate','transcriptEngine']);if(b.transcriptCandidate!==undefined){if(b.kind!=='audio'||b.transcriptEngine!=='whisper-tiny-q8-wasm-local')fail('Invalid local transcript metadata');string(b.transcriptCandidate,100000);}else if(b.transcriptEngine!==undefined)fail('Transcript candidate required');string(b.mime,100);string(b.base64,24*1024*1024);if(!['photo','audio'].includes(b.kind))fail('Invalid media kind');if(b.base64.length>Math.ceil((b.kind==='photo'?8:16)*1024*1024/3)*4)fail('Decoded media too large',413);if(b.base64.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(b.base64))fail('Invalid base64');const bytes=Buffer.from(b.base64,'base64');if(bytes.toString('base64')!==b.base64)fail('Noncanonical base64');const canonical=sniff(b.kind,b.mime,bytes);let processed;try{processed=await media.processMedia({kind:b.kind,mime:canonical,buffer:bytes,storageDir:mediaDir});}catch{processed={...await missingMedia.processMedia({mime:canonical,buffer:bytes}),processing:'failed',detail:'미디어 처리 실패: 원본 첨부를 보존했어요.'};}if(!Buffer.isBuffer(processed.buffer))fail('Invalid media helper result',500);const mime=sniff(b.kind,processed.mime,processed.buffer);if(!['ready','unavailable','failed'].includes(processed.processing))fail('Invalid media helper processing',500);const id=randomUUID();const handle=await open(path.join(mediaDir,id),'wx',0o600);try{await handle.writeFile(processed.buffer);await handle.sync();}finally{await handle.close();}const item={id,kind:b.kind,mime,url:'/api/app/media/'+id,ocrText:b.kind==='photo'&&typeof processed.ocrText==='string'?processed.ocrText.slice(0,100000):null,transcript:b.kind==='audio'&&typeof processed.transcript==='string'?processed.transcript.slice(0,100000):null,processing:b.transcriptCandidate?'ready':processed.processing,transcriptCandidate:b.transcriptCandidate??null,transcriptEngine:b.transcriptEngine??null,detail:b.transcriptCandidate?'브라우저 로컬 Whisper 인식 후보예요. 실제 구조화에는 대화창에서 확인한 글만 사용해요.':String(processed.detail??'')};return reply({media:item},{media:item});}
 if(route==='/api/app/sessions'){keys(b,['text','attachmentIds','workedAt']);string(b.text,100000,true);if(!dateOK(b.workedAt))fail('Invalid workedAt');if(!Array.isArray(b.attachmentIds)||b.attachmentIds.length>10||new Set(b.attachmentIds).size!==b.attachmentIds.length)fail('Invalid attachments');const attachments=b.attachmentIds.map(id=>{if(typeof id!=='string'||!uuid.test(id)||!state.media[id])fail('Unknown attachment');return state.media[id];});if(!b.text.trim()&&!attachments.length)fail('Text or attachment required');const s={id:randomUUID(),workedAt:b.workedAt,messages:[{role:'user',text:b.text,created_at:now()}],draft:emptyDraft(b.workedAt),question:null,clarificationCount:0,engine:'local-fallback',warnings:[],attachments,ready:false,updated_at:now()};await extract(s,state.profile,ai);question(s,state.profile);return reply({session:s},s);}
 if((m=route.match(/^\/api\/app\/entries\/([^/]+)\/correct$/))){keys(b,[]);const e=filteredEntries(state).find(e=>e.id===m[1]);if(!e)fail('Current entry not found',404);const original=getSession(state,e.session_id);const s={...structuredClone(original),id:randomUUID(),draft:Object.fromEntries(Object.keys(emptyDraft()).map(k=>[k,e[k]])),supersedes:e.id,updated_at:now(),question:null,clarificationCount:2,ready:true};delete s.confirmedEntryId;return reply({session:s},s);}
 if(route==='/api/app/export'){keys(b,['from','to','parcel_id','reviewed']);if(b.reviewed!==true||!dateOK(b.from)||!dateOK(b.to))fail('Review and date range required');const {reviewed,...f}=b;return {value:buildExport(filteredEntries(state,f))};}
 if((m=route.match(/^\/api\/app\/sessions\/([^/]+)\/(messages|draft|confirm)$/))){const s=getSession(state,m[1]);const action=m[2];if(action!=='confirm'&&s.confirmedEntryId)fail('Saved session is immutable; create correction',409);
 if(action==='messages'){keys(b,['text','answerField']);string(b.text,100000);if(s.messages.length>100)fail('Session message limit reached',413);const field=b.answerField;if(field!==undefined&&field!==s.question?.field)fail('answerField must match current question');s.messages.push({role:'user',text:b.text,created_at:now()});if(field!==undefined){const value=b.text.trim();const next={...s.draft,[field]:value};s.draft=validateDraft(next,state.profile);}else if(!/^(스킵|건너뛰기|모르겠어요|skip)$/i.test(b.text.trim()))await extract(s,state.profile,ai);question(s,state.profile);}
 if(action==='draft'){keys(b,['draft']);s.draft=validateDraft(b.draft,state.profile);s.question=null;s.ready=Boolean(ready(s.draft));}
 if(action==='confirm'){keys(b,['reviewed','idempotencyKey','supersedes']);if(b.reviewed!==true||typeof b.idempotencyKey!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(b.idempotencyKey))fail('Explicit review and valid idempotency key required');if(b.supersedes!==undefined&&b.supersedes!==(s.supersedes??null))fail('Correction target is server-fixed',409);const digest=createHash('sha256').update(JSON.stringify({session:s.id,draft:s.draft,supersedes:s.supersedes??null,reviewed:true})).digest('hex');const prior=Object.hasOwn(state.idempotency,b.idempotencyKey)?state.idempotency[b.idempotencyKey]:null;if(prior){if(prior.digest!==digest)fail('Idempotency conflict',409);return {value:{entry:state.entries.find(e=>e.id===prior.entryId),duplicate:true}};}if(s.confirmedEntryId)fail('Session already confirmed',409);validateDraft(s.draft,state.profile);if(!ready(s.draft))fail('Four required fields must be completed');if(s.supersedes&&!filteredEntries(state).some(e=>e.id===s.supersedes))fail('Correction target is no longer current',409);const entry={...s.draft,id:randomUUID(),session_id:s.id,parcel_name:state.profile.parcels.find(p=>p.id===s.draft.parcel_id).name,created_at:now(),supersedes:s.supersedes??null,source_text:source(s),attachments:s.attachments,engine:s.engine,regulatory_status:'not_checked',reviewed:true};s.confirmedEntryId=entry.id;s.updated_at=now();return reply({session:s,entry,idempotency:{key:b.idempotencyKey,digest,entryId:entry.id}},{entry,duplicate:false});}
 s.updated_at=now();return reply({session:s},s);
 }
 fail('Not found',404);
 });return json(res,200,result);
 }catch(e){const status=e.status??(e instanceof URIError?400:e.code==='ENOENT'?404:500);if(!res.headersSent)json(res,status,{error:status<500?e.message:'Local processing or storage failed; no successful save is claimed'});else res.end();}
 });
 const nativeListen=server.listen.bind(server),nativeClose=server.close.bind(server);let closing;server.listen=(p=port,...args)=>{if(closing)throw new Error('Closed server');if(!Number.isInteger(p)||!(p===8880||p===0))throw new Error('Port 8880 only (0 reserved for tests)');if(args.some(a=>typeof a!=='function'&&a!=='127.0.0.1'))throw new Error('127.0.0.1 only');return nativeListen(p,'127.0.0.1',args.find(a=>typeof a==='function'));};server.close=cb=>{closing??=new Promise((resolve,reject)=>nativeClose(e=>store.close().then(()=>e&&e.code!=='ERR_SERVER_NOT_RUNNING'?reject(e):resolve(),reject)));if(cb)closing.then(()=>cb(),cb);else closing.catch(e=>console.error('Close failed:',e.message));return server;};return server;
 }catch(e){await store.close();throw e;}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const server=await createFarmerServer();const close=()=>server.close(e=>{if(e){console.error(e.message);process.exitCode=1;}});process.once('SIGTERM',close);process.once('SIGINT',close);if(typeof process.send==='function')process.on('message',m=>{if(m?.type==='farm-log-dev-reload')server.close(e=>process.exit(e?1:0));});server.once('error',e=>{console.error(e.message);process.exitCode=1;close();});server.listen(8880,()=>console.log('FarmLog local farmer app http://127.0.0.1:8880'));}
